import React from 'react'
import { GhostButton, Badge, SourceBadge, EmptyState } from './ui'
import { advApi, f1, Plan } from '../lib/twin'

export default function AnalysisTab({ plan, analysis, run }: { plan: Plan | null; analysis: any; run: (k: string, fn: () => Promise<any>) => () => void }) {
  if (!plan) return <EmptyState title="Optimize first" hint="Analyses run on the active plan." />
  const btn = (k: string, label: string, fn: () => Promise<any>) => <GhostButton key={k} onClick={run(k, fn)} disabled={analysis[k]?.loading}>{analysis[k]?.loading ? '…' : label}</GhostButton>
  return (
    <div className="space-y-3">
      <div className="flex flex-wrap gap-2">{btn('explain', 'Explain plan', advApi.explain)}{btn('dna', 'Route DNA', () => advApi.dna(false))}{btn('tw', 'Time windows', advApi.timeWindows)}{btn('res', 'Resilience', () => advApi.resilience({ maxIterations: 40 }))}{btn('reg', 'Regret', () => advApi.regret({ maxIterations: 40 }))}</div>
      {analysis.explain?.sentences && <div className="text-xs text-slate-300 space-y-1">{analysis.explain.sentences.map((s: string, i: number) => <p key={i}>{s}</p>)}<div className="space-y-1 mt-2">{analysis.explain.factors.filter((f: any) => f.contribution > 0).map((f: any) => <div key={f.key} className="flex items-center gap-2"><span className="w-24 text-slate-400">{f.factor}</span><div className="flex-1 h-2 rounded bg-slate-800"><div className="h-2 rounded bg-gradient-to-r from-saffron to-accent" style={{ width: `${Math.min(100, f.sharePct)}%` }} /></div><span className="w-12 text-right">{f.sharePct}%</span></div>)}</div><div className="text-[10px] text-slate-500">Terms sum to fitness exactly: {String(analysis.explain.identity)}</div></div>}
      {analysis.dna?.routeDna && <div className="text-xs rounded-xl bg-slate-900/50 border border-slate-800 p-3 space-y-1"><div className="font-mono text-accent">{analysis.dna.routeDna.id}</div><div className="text-slate-400 break-all">fingerprint {analysis.dna.routeDna.datasetFingerprint}</div><div className="text-slate-400">{analysis.dna.routeDna.algorithm} · seed {analysis.dna.routeDna.seed} · twin v{analysis.dna.routeDna.twinVersion}</div></div>}
      {analysis.tw?.stops && <div><div className="flex gap-1.5 flex-wrap mb-2">{Object.entries(analysis.tw.counts).map(([k, v]) => <Badge key={k} tone={k === 'SAFE' ? 'green' : k === 'AT RISK' ? 'yellow' : k === 'LIKELY VIOLATION' ? 'orange' : 'red'}>{k}: {String(v)}</Badge>)}<SourceBadge source="PREDICTED" /></div><table className="w-full text-[11px]"><thead className="text-slate-500"><tr><th className="text-left">Stop</th><th>Veh</th><th>Slack</th><th>Status</th></tr></thead><tbody>{analysis.tw.stops.slice().sort((a: any, b: any) => b.risk - a.risk).map((s: any) => <tr key={s.deliveryId} className="border-t border-slate-800/70"><td className="py-1">{s.deliveryId} <span className="text-slate-500">{s.label}</span></td><td className="text-center">{s.vehicleId}</td><td className="text-center">{f1(s.slackMin)}m</td><td className="text-center">{s.status}</td></tr>)}</tbody></table></div>}
      {analysis.res?.scenarios && <div><div className="flex items-center gap-2 mb-2"><b className="text-sm">Resilience {analysis.res.score}/100</b><SourceBadge source="SIMULATED" /></div><table className="w-full text-[11px]"><thead className="text-slate-500"><tr><th className="text-left">Scenario</th><th>Δ delay</th><th>Unserved</th><th>Result</th></tr></thead><tbody>{analysis.res.scenarios.map((s: any) => <tr key={s.scenario} className="border-t border-slate-800/70"><td className="py-1">{s.scenario}</td><td className="text-center">{f1(s.delayMin)}m</td><td className="text-center">{s.missedDeliveries}</td><td className="text-center"><Badge tone={s.survived ? 'green' : s.recoveredByReoptimization ? 'yellow' : 'red'}>{s.survived ? 'survives' : s.recoveredByReoptimization ? 'recoverable' : 'fails'}</Badge></td></tr>)}</tbody></table><p className="text-[10px] text-slate-500 mt-2">{analysis.res.methodology}</p></div>}
      {analysis.reg?.scenarios && <div><div className="flex items-center gap-2 mb-2"><b className="text-sm">Regret</b><SourceBadge source="SIMULATED" /></div><table className="w-full text-[11px]"><thead className="text-slate-500"><tr><th className="text-left">Scenario</th><th>Regret (fitness)</th><th>Regret (min)</th><th className="text-left">Best alternative</th></tr></thead><tbody>{analysis.reg.scenarios.map((s: any) => <tr key={s.scenario} className="border-t border-slate-800/70"><td className="py-1">{s.scenario}</td><td className="text-center">{f1(s.regretFitness)} ({f1(s.regretPct)}%)</td><td className="text-center">{f1(s.regretMin)}</td><td className="truncate max-w-[140px]">{s.bestAlternative}</td></tr>)}</tbody></table><p className="text-[10px] text-slate-500 mt-2">{analysis.reg.definition}</p></div>}
    </div>
  )
}
