/**
 * FRIDAY's labelled utterance set. It is used three ways:
 *   1. as the training corpus of the on-device TF-IDF intent classifier (friday/classifier.ts) — this is the
 *      "trained model" that works with NO external LLM and no network,
 *   2. as few-shot examples injected into the Groq/Gemini tool-selection prompt,
 *   3. (with HELD_OUT below) as the evaluation set in tests/friday.test.ts, which asserts a minimum accuracy.
 * Adding examples here is how FRIDAY is "trained" — no fine-tuning of a hosted model is involved or claimed.
 */
export interface Example { text: string; tool: string }
const E = (tool: string, ...texts: string[]): Example[] => texts.map((text) => ({ text, tool }));

export const TRAINING: Example[] = [
  ...E('system.get_health', 'how is the system doing', 'system health', 'is everything running', 'give me a status report of the platform', 'check platform health'),
  ...E('system.self_check', 'run a self check', 'verify all subsystems', 'run diagnostics on the platform', 'test every module and tell me what passes', 'run the health verification'),
  ...E('traffic.get_current_status', 'what is the traffic status', 'how is traffic right now', 'show current congestion', 'how bad is congestion in the city', 'traffic conditions please', 'what is the average congestion'),
  ...E('traffic.get_incidents', 'any incidents right now', 'list active incidents', 'are there accidents on the road', 'show me current incidents', 'what incidents are open'),
  ...E('weather.get_current', 'what is the weather', 'how is the weather in pune', 'is it raining', 'current temperature', 'tell me the weather now'),
  ...E('weather.simulate_weather', 'simulate heavy rain', 'simulate a storm on the network', 'switch weather to fog', 'make it rain heavily in the simulation', 'set weather to clear sky'),
  ...E('fleet.list', 'show fleet status', 'how is my fleet doing', 'list all vehicles', 'where are my vehicles', 'fleet overview', 'how many vehicles are on route'),
  ...E('fleet.get_vehicle', 'where is q-01', 'status of vehicle q-03', 'tell me about q-02', 'what is q-04 doing', 'locate vehicle q-05'),
  ...E('fleet.reroute_vehicle', 'reroute q-01', 'find a new route for q-02', 'reroute vehicle q-03 around traffic', 'recalculate the route of q-04'),
  ...E('fleet.reroute_all_delayed', 'reroute all delayed vehicles', 'fix every delayed vehicle', 'recalculate routes for all delayed trucks'),
  ...E('fleet.assign_task', 'assign q-01 to hinjewadi', 'dispatch q-02 to koregaon park', 'send vehicle q-03 to kharadi', 'assign a delivery to q-04 at baner'),
  ...E('fleet.why_reassigned', 'why was vehicle q-02 reassigned', 'why did the deliveries move to another vehicle', 'why was q-01 reassigned after the breakdown', 'explain the fleet reallocation', 'who took over the broken vehicles deliveries'),
  ...E('optimization.run', 'run the optimizer', 'optimize the routes', 'start route optimization', 'open the planner and optimize'),
  ...E('optimization.benchmark', 'open benchmarking', 'show me the benchmark page', 'take me to algorithm benchmarking'),
  ...E('optimization.convergence', 'show the convergence chart', 'open convergence for the latest run', 'how did the optimizer converge on the page'),
  ...E('map.set_mode', 'switch the map to night mode', 'make the map dark', 'use day map', 'light map please'),
  ...E('navigation.open', 'open the dashboard', 'go to notifications', 'show settings', 'open the history page', 'take me to the command center', 'show scalability page'),
  ...E('incidents.create_incident', 'trigger an accident', 'create a road closure incident', 'simulate an accident on the network', 'report a road closure'),
  ...E('incidents.resolve_incident', 'resolve the incident', 'clear the accident', 'close the incident report', 'the incident is over'),
  ...E('analytics.get_statistics', 'how many optimization runs have we done', 'show optimization statistics', 'analytics summary', 'how many runs are recorded'),
  ...E('citizen.delivery_status', 'where is my package', 'what is my eta', 'is my delivery delayed', 'my delivery status'),
  ...E('twin.get_state', 'show the digital twin state', 'what does the twin look like right now', 'summarize the current twin', 'what is in the digital twin', 'give me the current network and fleet state', 'twin status'),
  ...E('twin.optimize', 'optimize the digital twin with qpso', 'run adaptive qpso on the twin', 'plan the deliveries with pso', 'compute a new plan using genetic algorithm', 'generate the delivery plan'),
  ...E('twin.get_state', 'twin summary', 'digital twin overview', 'what is the state of the twin'),
  ...E('twin.what_if', 'what happens if road r-142 closes', 'what if there is an accident on baner road', 'what if traffic increases by 40 percent', 'what would happen if q-02 breaks down', 'what if it rains heavily', 'simulate closure of r-120 without changing the live twin', 'what if the pune satara highway is blocked'),
  ...E('twin.apply_event', 'close road r-115 now', 'apply a 30 percent traffic increase to the twin', 'break down vehicle q-01', 'trigger an accident on nh48 in the twin', 'make q-03 unavailable', 'inject heavy rain into the twin'),
  ...E('twin.apply_event', 'apply a road closure to the twin', 'apply closure on r-140 to the digital twin', 'mark q-04 as broken down', 'set vehicle q-02 to broken down in the twin', 'inject an accident into the twin on r-101'),
  ...E('twin.reoptimize', 're-optimize the routes', 'recompute the plan after the incident', 'replan with adaptive qpso', 'rerun the optimization on the changed network', 'update the plan for the new conditions'),
  ...E('analysis.explain_route', 'why was this route selected', 'explain the current plan', 'why did the optimizer choose this route', 'explain the routing decision', 'what drove the fitness of this plan'),
  ...E('analysis.route_dna', 'show the route dna', 'what is the dna of this plan', 'give me the route fingerprint', 'route dna id'),
  ...E('analysis.resilience', 'how resilient is the current plan', 'what is the resilience score', 'test the plan against disruptions', 'run resilience analysis'),
  ...E('analysis.regret', 'what is the regret of this plan', 'how much do we regret this route choice', 'run regret analysis', 'what is the worst case regret'),
  ...E('analysis.time_windows', 'which deliveries are at risk of missing their time windows', 'time window risk', 'show late deliveries risk', 'are any deliveries likely to be late'),
  ...E('analysis.counterfactual', 'what if we had not re-optimized', 'what would have happened if we did not reoptimize', 'counterfactual comparison', 'without re-optimization how late would we be'),
  ...E('analysis.counterfactual', 'what would have happened without re-optimization', 'counterfactual analysis', 'compare with and without re-optimization after an accident', 'how much delay did re-optimization avoid'),
  ...E('benchmark.compare', 'compare qpso and pso', 'is qpso better than ga', 'qpso versus simulated annealing', 'which algorithm is best', 'compare adaptive qpso with qpso', 'is the difference between qpso and pso statistically significant'),
  ...E('benchmark.explain', 'explain the benchmark results', 'what does the benchmark show', 'summarize the latest benchmark', 'how fair was the benchmark', 'what hardware was the benchmark run on'),
  ...E('scalability.explain', 'how does the system scale', 'explain the scalability results', 'what happens with 500 customers', 'can it handle a thousand deliveries', 'scalability test explanation'),
  ...E('learning.summary', 'what did the system learn', 'what has the model learned from history', 'how good are the eta predictions', 'prediction accuracy of the planner'),
  ...E('learning.summary', 'how accurate were our eta predictions', 'actual versus predicted summary', 'what has the system learned from past deliveries', 'eta prediction error', 'show the learning loop results'),
  ...E('demo.control', 'start the sih demo', 'begin the demonstration', 'pause the demo', 'resume the demo', 'reset the demo', 'what step is the demo on', 'run the full presentation'),
  ...E('algorithm.explain', 'what is adaptive qpso', 'explain adaptive qpso', 'what is quantum inspired', 'is qpso real quantum computing', 'what is pso', 'explain the genetic algorithm'),
  ...E('fleet.list', 'how many trucks are moving', 'how many vehicles are active', 'give me a fleet summary'),
  ...E('fleet.get_vehicle', 'give me details on q-01', 'details for vehicle q-02', 'give me the details of q-03'),
  ...E('algorithm.explain', 'what is qpso', 'explain quantum inspired optimization', 'is this real quantum computing', 'how does adaptive qpso work', 'what is the difference between qpso and pso', 'does this use a quantum computer', 'explain the objective function'),
];

/** Held out during training — used only to measure the classifier in tests. Paraphrases, not copies. */
export const HELD_OUT: Example[] = [
  ...E('traffic.get_current_status', 'tell me about congestion levels', 'is traffic heavy at the moment'),
  ...E('traffic.get_incidents', 'are there any accidents reported', 'what incidents are currently active'),
  ...E('fleet.list', 'give me the fleet summary', 'how many trucks are moving'),
  ...E('fleet.get_vehicle', 'where is vehicle q-06 right now', 'give me details on q-01'),
  ...E('twin.get_state', 'describe the digital twin', 'twin summary please'),
  ...E('twin.what_if', 'what if road r-130 is closed', 'what happens if traffic rises 25 percent', 'what if q-01 breaks down'),
  ...E('twin.apply_event', 'apply a road closure on r-118 to the twin', 'mark q-02 as broken down'),
  ...E('twin.reoptimize', 'recompute routes now', 'please re-optimize the plan'),
  ...E('analysis.explain_route', 'why did you pick this route', 'explain why this plan was chosen'),
  ...E('analysis.route_dna', 'what is the route dna id', 'show dna fingerprint of the plan'),
  ...E('analysis.resilience', 'how robust is the plan', 'resilience score of the current routes'),
  ...E('analysis.regret', 'what is the regret analysis', 'compute regret for this plan'),
  ...E('analysis.time_windows', 'which stops might miss their windows', 'time window risk report'),
  ...E('analysis.counterfactual', 'what if we had not re-optimized', 'counterfactual comparison please'),
  ...E('fleet.why_reassigned', 'why was q-03 reassigned', 'explain why deliveries moved between vehicles'),
  ...E('benchmark.compare', 'compare qpso against ga', 'does adaptive qpso beat qpso'),
  ...E('benchmark.explain', 'explain the benchmark', 'what were the benchmark results'),
  ...E('learning.summary', 'how good were the eta predictions', 'what did the system learn'),
  ...E('demo.control', 'start the demo', 'pause the presentation'),
  ...E('algorithm.explain', 'is qpso quantum computing', 'what is adaptive qpso'),
  ...E('weather.get_current', 'how is the weather right now'),
  ...E('system.self_check', 'run self diagnostics'),
];
