import React,{useMemo,useState} from 'react'
import {useMutation,useQuery,useQueryClient} from '@tanstack/react-query'
import {ShieldCheck,Users,Route as RouteIcon,AlertTriangle,Database,Radio,Truck,MapPin,CloudRain,Play,Navigation,Activity,Zap} from 'lucide-react'
import {BarChart,Bar,XAxis,YAxis,Tooltip,ResponsiveContainer,CartesianGrid} from 'recharts'
import api from '../api/client'
import {GlassCard,KpiCard,Badge,PrimaryButton,Select,Input} from '../components/ui'
import QRouteMap from '../components/QRouteMap'
import {useSocket} from '../lib/useSocket'
import {useOptimizationStore} from '../store/optimizationStore'

const ADMIN_COLORS = ['#3b82f6','#10b981','#f59e0b','#ef4444','#8b5cf6','#ec4899','#06b6d4','#f97316','#84cc16','#e11d48','#14b8a6','#a855f7'];
const SCENARIOS=[['ACCIDENT','Accident'],['ROAD_CLOSURE','Road closure'],['RUSH_HOUR','Rush hour'],['HEAVY_RAIN','Heavy rain'],['RANDOM_CONGESTION','Random congestion']]
export default function Admin(){
 const {fleetOptimizationResult} = useOptimizationStore();
 const qc=useQueryClient();const [incidentPoint,setIncidentPoint]=useState<any>(null);const [type,setType]=useState('ACCIDENT');const [severity,setSeverity]=useState('HIGH');const [description,setDescription]=useState('Admin reported accident');const [selectedId,setSelectedId]=useState('Q-01');
 const {data:dashboard}=useQuery({queryKey:['admin-dashboard'],queryFn:async()=>(await api.get('/admin/dashboard')).data,refetchInterval:8000});
 const {data:users}=useQuery({queryKey:['admin-users'],queryFn:async()=>(await api.get('/admin/users')).data});
 const {data:comparison}=useQuery({queryKey:['admin-optimization'],queryFn:async()=>(await api.get('/admin/optimization')).data});
 const {data:fleet}=useQuery({queryKey:['admin-fleet'],queryFn:async()=>(await api.get('/fleet')).data,refetchInterval:3000});
 const {data:traffic}=useQuery({queryKey:['admin-traffic'],queryFn:async()=>(await api.get('/traffic')).data,refetchInterval:6000});
 const {data:incidents}=useQuery({queryKey:['admin-incidents'],queryFn:async()=>(await api.get('/traffic/incidents')).data,refetchInterval:5000});
 const {data:weather}=useQuery({queryKey:['admin-weather'],queryFn:async()=>(await api.get('/weather?lat=18.5204&lon=73.8567')).data,refetchInterval:60000});
 const {connected}=useSocket('fleet');
 const adminMultiRoutes = useMemo(() => {
   if (!fleetOptimizationResult?.routes) return [];
   return fleetOptimizationResult.routes.map((r:any, i:number) => ({ vehicleId: r.vehicleId, geometry: r.geometry||[], color: ADMIN_COLORS[i%ADMIN_COLORS.length] }));
 }, [fleetOptimizationResult]);
 const dispatchedCount = fleetOptimizationResult?.routes?.length ?? 0;
 const compData=Object.entries(comparison?.comparison||{}).map(([algo,v]:[string,any])=>({algorithm:algo,avgFitness:Math.round(v.avgFitness*10)/10}));
 const selected=(fleet?.vehicles||[]).find((v:any)=>v.id===selectedId)||fleet?.vehicles?.[0];
 const create=useMutation({mutationFn:async()=>{if(!incidentPoint)throw new Error('Click the map first');return (await api.post('/traffic/incidents/manual',{type,lat:incidentPoint.lat,lon:incidentPoint.lon,severity,description})).data},onSuccess:()=>{setIncidentPoint(null);qc.invalidateQueries({queryKey:['admin-incidents']});qc.invalidateQueries({queryKey:['admin-dashboard']})}});
 const simulate=useMutation({mutationFn:async(key:string)=>(await api.post('/traffic/simulate',{scenarioType:key})).data,onSuccess:()=>{qc.invalidateQueries({queryKey:['admin-incidents']});qc.invalidateQueries({queryKey:['admin-traffic']})}});
 const resolve=useMutation({mutationFn:async(id:string)=>(await api.post(`/traffic/incidents/${id}/resolve`)).data,onSuccess:()=>qc.invalidateQueries({queryKey:['admin-incidents']})});
 const mapIncidents=useMemo(()=> (incidents?.incidents||[]).filter((i:any)=>i.lat&&i.lon).map((i:any)=>({lat:i.lat,lon:i.lon,label:`${i.type} · ${i.severity}` })),[incidents]);
  const handleMapClick = async (p: any) => {
    setIncidentPoint(p);
    try {
      const res = await api.get(`/maps/reverse-geocode?lat=${p.lat}&lon=${p.lon}`);
      if (res.data && res.data.displayName) {
        setDescription(`Incident at ${res.data.displayName.split(',')[0]}`);
      }
    } catch {}
  };
  
  const [city, setCity] = useState(() => localStorage.getItem('quantara_city') || 'Pune');
  return <div className="space-y-5">
  <div className="flex flex-col lg:flex-row lg:items-center justify-between gap-3"><div><div className="text-[10px] uppercase tracking-[.22em] text-accent flex items-center gap-2"><ShieldCheck size={13}/> Administrator command center</div><h1 className="font-display text-2xl lg:text-3xl font-semibold mt-1">QUANTARA Control Room</h1><p className="text-slate-500 text-sm">One admin surface for fleet, routing, traffic, weather, optimization and map operations.</p></div><div className="flex gap-2 items-center"><Select value={city} onChange={e=>{setCity(e.target.value); localStorage.setItem('quantara_city', e.target.value); window.dispatchEvent(new CustomEvent('quantara:city-change', { detail: { city: e.target.value } }));}} className="bg-slate-800 border border-slate-700 text-xs py-1"><option>Pune</option><option>Mumbai</option><option>Delhi</option><option>Bengaluru</option><option>Hyderabad</option><option>Chennai</option><option>Kolkata</option></Select><Badge tone="green">GPS {connected?'LIVE':'RECONNECT'}</Badge><Badge tone={traffic?.source==='LIVE'?'green':'yellow'}>TRAFFIC {traffic?.source||'—'}</Badge></div></div>
  <div className="grid grid-cols-2 lg:grid-cols-8 gap-2.5"><KpiCard label="Live Vehicles" value={fleet?.vehicles?.length??0} icon={<Truck size={15}/>}/><KpiCard label="On Route" value={(fleet?.vehicles||[]).filter((v:any)=>v.status==='ON_ROUTE').length} icon={<Navigation size={15}/>}/><KpiCard label="Delayed" value={(fleet?.vehicles||[]).filter((v:any)=>v.status==='DELAYED').length} icon={<Activity size={15}/>}/><KpiCard label="Dispatched" value={dispatchedCount} accent="quantum" icon={<Zap size={15}/>}/><KpiCard label="Active Routes" value={adminMultiRoutes.length} accent="accent" icon={<RouteIcon size={15}/>}/><KpiCard label="Congestion" value={traffic?.avgCongestionPct??0} suffix="%" accent="quantum" icon={<Radio size={15}/>}/><KpiCard label="Incidents" value={incidents?.incidents?.length??0} accent="saffron" icon={<AlertTriangle size={15}/>}/><KpiCard label="Weather" value={weather?.temperature??'—'} suffix={weather?.temperature!=null?'°C':''} icon={<CloudRain size={15}/>}/></div>
  <div className="grid grid-cols-1 xl:grid-cols-[240px_minmax(0,1fr)_320px] gap-3">
   <GlassCard className="p-0 overflow-hidden min-h-[620px]"><div className="px-4 py-3 border-b border-slate-800/70"><div className="text-[10px] text-slate-500 uppercase tracking-widest">Fleet dispatch</div><div className="font-semibold mt-1">{fleet?.vehicles?.length??0} units</div></div><div className="divide-y divide-slate-800/60">{(fleet?.vehicles||[]).map((v:any)=><button key={v.id} onClick={()=>setSelectedId(v.id)} className={`w-full text-left p-3 ${selectedId===v.id?'bg-accent/10 border-l-2 border-accent':'hover:bg-slate-800/50'}`}><div className="flex justify-between"><span className="font-mono text-xs">{v.id}</span><Badge tone={v.status==='DELAYED'?'yellow':v.status==='OFFLINE'?'default':'green'}>{v.status.replace('_',' ')}</Badge></div><div className="text-[10px] text-slate-500 mt-1">{v.matchedRoad}</div><div className="flex justify-between text-[10px] mt-2"><span>{v.speed} km/h</span><span>{v.eta}</span></div></button>)}</div></GlassCard>
   <GlassCard className="p-0 overflow-hidden min-h-[620px] relative"><div className="absolute z-10 top-3 left-3 right-3 flex justify-between pointer-events-none"><div className="glass-strong rounded-xl px-3 py-2 text-[10px]">ADMIN EDIT MODE · click map to place an incident</div><div className="glass-strong rounded-xl px-3 py-2 text-[10px] text-accent">3D · LIVE ROAD VIEW{adminMultiRoutes.length>0?` · ${adminMultiRoutes.length} dispatch routes`:''}</div></div><QRouteMap height="620px" vehicles={(fleet?.vehicles||[]).map((v:any)=>({id:v.id,lat:v.lat,lon:v.lon,speed:v.speed,status:v.status,eta:v.eta,deliveries:v.deliveries,heading:v.heading}))} multiRoutes={adminMultiRoutes.length>0?adminMultiRoutes:undefined} incidents={mapIncidents} onMapClick={handleMapClick} fitRoute={false}/>{incidentPoint&&<div className="absolute bottom-3 left-3 z-10 glass-strong rounded-xl px-3 py-2 text-xs max-w-[80%]"><MapPin size={12} className="inline text-accent mr-1"/>  New spot: {incidentPoint.lat.toFixed(5)}, {incidentPoint.lon.toFixed(5)}<div className="text-[10px] text-slate-400 mt-1">{description}</div></div>}</GlassCard>
   <div className="space-y-3"><GlassCard><div className="text-sm font-semibold mb-3">Map incident editor</div><div className="space-y-2"><Select className="w-full" value={type} onChange={e=>setType(e.target.value)}>{['ACCIDENT','ROAD_CLOSURE','HAZARD','FLOOD','HEAVY_RAIN','CONGESTION'].map(x=><option key={x}>{x}</option>)}</Select><Select className="w-full" value={severity} onChange={e=>setSeverity(e.target.value)}>{['LOW','MODERATE','HIGH','SEVERE'].map(x=><option key={x}>{x}</option>)}</Select><Input className="w-full" value={description} onChange={e=>setDescription(e.target.value)} placeholder="What happened?"/><PrimaryButton disabled={!incidentPoint||create.isPending} onClick={()=>create.mutate()} className="w-full">{create.isPending?'Updating map…':'Publish incident to live map'}</PrimaryButton></div></GlassCard>
   <GlassCard><div className="text-sm font-semibold mb-3">Traffic controls</div><div className="grid grid-cols-1 gap-2">{SCENARIOS.map(([k,l])=><button key={k} onClick={()=>simulate.mutate(k)} className="text-left rounded-xl px-3 py-2 bg-slate-900/60 border border-slate-800 text-xs hover:border-accent/30 flex items-center justify-between"><span>{l}</span><Play size={12} className="text-accent"/></button>)}</div></GlassCard>
   <GlassCard><div className="text-sm font-semibold mb-3">Selected telemetry</div>{selected?<div className="space-y-2 text-xs"><div className="flex justify-between"><span className="text-slate-500">Road</span><span>{selected.matchedRoad}</span></div><div className="flex justify-between"><span className="text-slate-500">Speed</span><span>{selected.speed} km/h</span></div><div className="flex justify-between"><span className="text-slate-500">GPS</span><span>{selected.locationSource} · {selected.confidencePct}%</span></div><div className="flex justify-between"><span className="text-slate-500">Remaining</span><span>{selected.distanceRemainingKm} km</span></div></div>:<div className="text-xs text-slate-500">No vehicle selected.</div>}</GlassCard></div>
  </div>
  <div className="grid grid-cols-1 lg:grid-cols-2 gap-3"><GlassCard><div className="flex items-center justify-between mb-3"><h3 className="text-sm font-medium">Active incidents</h3><Badge tone="yellow">ADMIN CONTROL</Badge></div><div className="space-y-2 max-h-72 overflow-auto">{(incidents?.incidents||[]).map((i:any)=><div key={i.id} className="flex items-center justify-between gap-3 rounded-xl bg-slate-900/40 p-3"><div><div className="text-xs font-medium">{i.type}</div><div className="text-[10px] text-slate-500">{i.description}</div><div className="text-[9px] text-slate-600 mt-1">{i.lat?.toFixed?.(5)}, {i.lon?.toFixed?.(5)} · {i.provider||i.source}</div></div><div className="flex items-center gap-2"><Badge tone={i.severity==='HIGH'||i.severity==='SEVERE'?'red':'yellow'}>{i.severity}</Badge>{i.id&&<button onClick={()=>resolve.mutate(i.id)} className="text-[10px] text-slate-500 hover:text-red-300">Resolve</button>}</div></div>)}{!(incidents?.incidents||[]).length&&<div className="text-xs text-slate-600">No active incidents.</div>}</div></GlassCard>
  <GlassCard><h3 className="text-sm font-medium mb-3">Optimization intelligence</h3>{compData.length?<ResponsiveContainer width="100%" height={230}><BarChart data={compData}><CartesianGrid strokeDasharray="3 3" stroke="#1c2942"/><XAxis dataKey="algorithm" stroke="#64748b" fontSize={11}/><YAxis stroke="#64748b" fontSize={11}/><Tooltip/><Bar dataKey="avgFitness" fill="#a78bfa" radius={[6,6,0,0]}/></BarChart></ResponsiveContainer>:<div className="text-xs text-slate-500">No optimization runs yet. Open Plan & Optimize to run QPSO/PSO/GA/SA.</div>}</GlassCard></div>
  <GlassCard><div className="flex items-center gap-2 mb-3"><Users size={15} className="text-accent"/><h3 className="text-sm font-medium">User and system administration</h3></div><div className="grid grid-cols-2 md:grid-cols-4 gap-3 text-xs"><div><span className="text-slate-500">Users</span><div className="text-lg font-semibold">{dashboard?.totalUsers??users?.users?.length??0}</div></div><div><span className="text-slate-500">Optimization runs</span><div className="text-lg font-semibold">{dashboard?.totalOptimizationRuns??0}</div></div><div><span className="text-slate-500">Database</span><div className="text-lg font-semibold flex items-center gap-1"><Database size={13}/>{dashboard?.database?.backend||'—'}</div></div><div><span className="text-slate-500">Map authority</span><div className="text-lg font-semibold text-accent">ADMIN</div></div></div></GlassCard>
 </div>
}
